name: E2E Test(Playwright) - fetoolkit/admin-react
on:
  pull_request:
    branches:
      - 'dev-v**'
      - '!feature/issue-**'
      - '!bug/issue-**'
      - '!docs/issue-**'
    paths:
      - 'apps/admin-react-test/**'
      - 'packages/admin-react/src/**'
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build packages
        run: yarn build
      - name: Run test
        run: yarn tests:admin-react:e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
