name: Unit Test(Vitest) - fetoolkit/react
on:
  pull_request:
    branches:
      - 'dev-v**'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install -g yarn && yarn
      - name: Run test
        run: yarn packages:react test:unit
